<!doctype html>
<html lang=" en-US ">

<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?">
    <meta http-equiv="X-UA-Compatible" content="chrome=1"> <!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Exercises: Exceptions and Promises | Desarrollo y Mantenimiento de Sistemas Informáticos</title>
<meta name="generator" content="Jekyll v3.9.2" />
<meta property="og:title" content="Exercises: Exceptions and Promises" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="4º. 1er cuatrimestre. Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL" />
<meta property="og:description" content="4º. 1er cuatrimestre. Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL" />
<meta property="og:site_name" content="Desarrollo y Mantenimiento de Sistemas Informáticos" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Exercises: Exceptions and Promises" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebPage","description":"4º. 1er cuatrimestre. Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL","headline":"Exercises: Exceptions and Promises","url":"/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="/assets/css/style.css?v=9ea47fa642cb66de9ce818300978ad263daa076e">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="/assets/js/respond.js"></script>


    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>

    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="/assets/css/ie.css">
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

</head>

<body>
    <div id="header">
        <nav>
        <ul>
            <li><a href="/search">Search</a></li>
            <li><a href="https://ull-pl.vercel.app/resources" target="_blank">Rec</a></li>
            <li><a href="/timetables.html">Hor</a></li>
            <li><a href="/references.html">Refs</a></li>
            <li><a href="/clases.html">Clases</a></li>
            <li><a href="/practicas.html">Prácticas </a></li> 
            <li><a href="/index.html">DMSI</a></li>
            
        </ul>
        </nav>
    </div>
    <!-- end header -->


    <div class="wrapper">

        <section>
            <div id="title">
                <h1>Desarrollo y Mantenimiento de Sistemas Informáticos</h1>
                <p> 4º. 1er cuatrimestre. Itinerario de Sistemas de la Información. Grado en Ingeniería Informática. ULL</p>
                <hr>
                <span class="credits left"> <a href="https://github.com/ULL-ESIT-DMSI-2425" target="_blank">GH Org</a></span>
                <span class="credits left"> &nbsp; - <a href="https://github.com/ULL-ESIT-DMSI" target="_blank">GH Template Org</a></span>
                <span class="credits left"> &nbsp; - <a href="https://classroom.github.com/classrooms/176799893-ull-esit-dmsi-2425" target="_blank">GitHub Classroom</a></span>
                <span class="credits left"> &nbsp; - <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/discussions" target="_blank">Discussions</a></span>
                <span class="credits left"> &nbsp; - <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/teams" target="_blank">Teams</a></span>
                <span class="credits left"> &nbsp; - <a href="https://campusingenieriaytecnologia2425.ull.es/course/view.php?id=2425090032" target="_blank">Campus ULL</a></span>
                <span class="credits left"> &nbsp; - <a href="/teams" target="_blank">Students Activity</a></span>
                <span class="credits left"> &nbsp; - <a href="https://mail.google.com/chat/u/1/" target="_blank">Chat</a></span>
                <span class="credits left"> &nbsp; - <a href="https://meet.google.com/apb-imai-hsq" target="_blank">Google Meet</a></span>
                <!-- https://www.ull.es/apps/guias/guias/view_guide_course/2425/139264413/3/ -->

            </div>

            <h1 id="exercises-exceptions-and-promises">Exercises: Exceptions and Promises</h1>

<h2 id="first-exercise-exception-inside-the-action-of-a-promise">First Exercise: Exception inside the action of a Promise</h2>

<p>(Blog view at <a href="https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/">https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/</a>)</p>

<p>Remember that the code of a <strong><a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/executor.html">promise executor</a></strong> and <strong>promise handlers</strong> has an “invisible <code class="language-plaintext highlighter-rouge">try..catch</code>” around it.</p>

<p>If an exception happens, it gets caught and treated as a rejection.</p>

<p><strong>Will the message <code class="language-plaintext highlighter-rouge">"Everything worked!"</code> appear?</strong> (See <a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/exception-inside.html">exception-inside.html</a>)</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code>   <span class="kd">let</span> <span class="nx">p</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span>  <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="k">throw</span> <span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Que fallo!</span><span class="dl">"</span><span class="p">));</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">"</span><span class="s2">Everything worked! </span><span class="dl">"</span><span class="o">+</span><span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p><strong>What will be the ouput of this variant of the former code?</strong> (See <a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/exception-inside-2.html">exception-inside-2.html</a>)</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code>   <span class="kd">let</span> <span class="nx">p</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span>  <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="k">try</span> <span class="p">{</span>
        <span class="k">throw</span> <span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Que fallo!</span><span class="dl">"</span><span class="p">));</span>
      <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
        <span class="nx">reject</span><span class="p">(</span> <span class="dl">"</span><span class="s2">tilin!</span><span class="dl">"</span><span class="p">);</span>
      <span class="p">}</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">"</span><span class="s2">Everything worked! </span><span class="dl">"</span><span class="o">+</span><span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p><strong>What will be the rejection value of the promise?</strong></p>

<h2 id="second-exercise-exception-delayed-with-settimeout-inside-the-action-of-a-promise">Second Exercise: Exception Delayed with setTimeout inside the action of a Promise</h2>

<p>(Blog at <a href="https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/">https://ull-mii-sytws-1920.github.io/tema2-async/exercises/promises/exception-inside-promise/</a>)</p>

<p><strong>What do you think? Will the <code class="language-plaintext highlighter-rouge">.catch</code> trigger?</strong></p>

<p>See the code in <a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/exception-delayed.html">exception-delayed.html</a>:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="kd">function</span><span class="p">(</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Whoops!</span><span class="dl">"</span><span class="p">);</span>
  <span class="p">},</span> <span class="mi">1000</span><span class="p">);</span>
</code></pre></div></div>
<p>Explain your answer.</p>

<p>Remember that the code of a <strong><a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/executor.html">promise executor</a></strong> and <strong>promise handlers</strong> has an “invisible <code class="language-plaintext highlighter-rouge">try..catch</code>” around it.</p>

<p>If an exception happens, it gets caught and treated as a rejection.</p>

<p>Thus, the former code is equivalent to this <a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/exception-delayed-2.html">exception-delayed-2.html</a>:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code> <span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="kd">function</span><span class="p">(</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="p">{</span>
      <span class="k">try</span> <span class="p">{</span>
        <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
          <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Whoops!</span><span class="dl">"</span><span class="p">);</span>
        <span class="p">},</span> <span class="mi">1000</span><span class="p">);</span>
      <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span> <span class="nx">reject</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span> <span class="p">}</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span><span class="nx">alert</span><span class="p">);</span>
</code></pre></div></div>
<p>What is the sequences of actions taking place when this code executes?</p>

<p>Is the former code equivalent to this one (<a href="/assets/temas/introduccion-a-javascript/event-loop/exercises/promises/exception-inside-promise/exception-delayed-3.html">exception-delayed-3.html</a>)? :</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code>   <span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="kd">function</span><span class="p">(</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="p">{</span>
      <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
        <span class="k">try</span> <span class="p">{</span>
          <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Whoops!</span><span class="dl">"</span><span class="p">);</span>
        <span class="p">}</span> <span class="k">catch</span><span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
          <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">rejected </span><span class="dl">'</span><span class="o">+</span><span class="nx">e</span><span class="p">);</span>
        <span class="p">}</span>
      <span class="p">},</span> <span class="mi">1000</span><span class="p">);</span>
    <span class="p">}).</span><span class="k">catch</span><span class="p">(</span><span class="nx">alert</span><span class="p">);</span>
</code></pre></div></div>

<p>I have these examples here:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>~/.../promises/exception-inside-promise(master)]$ pwd -P
/Users/casiano/campus-virtual/1920/sytws1920/apuntes/tema2-async/exercises/promises/exception-inside-promise
</code></pre></div></div>

<h3 id="third-exercise-unhandled-rejection-event">Third Exercise: Unhandled Rejection Event</h3>

<p><strong>The “Unhandled rejection” event occurs when a promise error is not handled at the end of the microtask queue.</strong></p>

<p>Normally, if we expect an error, we add <code class="language-plaintext highlighter-rouge">.catch</code> to the promise chain to handle it:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">let</span> <span class="nx">promise</span> <span class="o">=</span> <span class="nb">Promise</span><span class="p">.</span><span class="nx">reject</span><span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">"</span><span class="s2">Promise Failed!</span><span class="dl">"</span><span class="p">));</span>
<span class="nx">promise</span><span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">err</span> <span class="o">=&gt;</span> <span class="nx">alert</span><span class="p">(</span><span class="dl">'</span><span class="s1">caught</span><span class="dl">'</span><span class="p">));</span>

<span class="c1">// doesn't run: error handled</span>
<span class="nb">window</span><span class="p">.</span><span class="nx">addEventListener</span><span class="p">(</span><span class="dl">'</span><span class="s1">unhandledrejection</span><span class="dl">'</span><span class="p">,</span> <span class="nx">event</span> <span class="o">=&gt;</span> <span class="nx">alert</span><span class="p">(</span><span class="nx">event</span><span class="p">.</span><span class="nx">reason</span><span class="p">));</span>
</code></pre></div></div>

<p>What if we handle the error later? We are going to use Node.js this time.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>~/.../promises/exception-inside-promise(master)]$ pwd -P
/Users/casiano/campus-virtual/1920/sytws1920/apuntes/tema2-async/exercises/promises/exception-inside-promise
~/.../promises/exception-inside-promise(master)]$ cat unhandled-promise-rejection.js 
</code></pre></div></div>

<p>Explain the behavior of this program:</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">#!/usr/bin/env node
</span><span class="dl">'</span><span class="s1">use strict</span><span class="dl">'</span><span class="p">;</span>

<span class="nx">process</span><span class="p">.</span><span class="nx">on</span><span class="p">(</span><span class="dl">'</span><span class="s1">unhandledRejection</span><span class="dl">'</span><span class="p">,</span> <span class="nx">error</span> <span class="o">=&gt;</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">unhandledRejection:</span><span class="dl">'</span><span class="p">,</span> <span class="nx">error</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="p">});</span>

<span class="kd">let</span> <span class="nx">p</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">reject</span><span class="p">(</span><span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">'</span><span class="s1">woops</span><span class="dl">'</span><span class="p">)));</span>

<span class="nx">setTimeout</span><span class="p">(</span> 
  <span class="p">()</span> <span class="o">=&gt;</span> <span class="nx">p</span><span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">error</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">caught</span><span class="dl">'</span><span class="p">,</span> <span class="nx">error</span><span class="p">.</span><span class="nx">message</span><span class="p">)),</span>
  <span class="mi">1000</span><span class="p">);</span>
</code></pre></div></div>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>[~/.../event-loop/promise-ejemplo(master)]$ ./unhandled-promise-rejection.js 
unhandledRejection: woops
caught woops
(node:107) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
</code></pre></div></div>

<p>Véase también
<a href="https://javascript.info/microtask-queue#unhandled-rejection">https://javascript.info/microtask-queue#unhandled-rejection</a>
para una versión de este programa  en el cliente/browser</p>

<h3 id="summarizing">Summarizing</h3>

<ol>
  <li><code class="language-plaintext highlighter-rouge">.catch</code> handles errors in promises of all kinds: be it a <code class="language-plaintext highlighter-rouge">reject()</code> call, or an error thrown in a handler.</li>
  <li>We should place <code class="language-plaintext highlighter-rouge">.catch</code> exactly in places where we want to handle errors and know how to handle them.</li>
  <li>It’s ok not to use <code class="language-plaintext highlighter-rouge">.catch</code> at all, if there’s no way to recover from an error.</li>
  <li>In any case we should have the <code class="language-plaintext highlighter-rouge">unhandledrejection</code> event handler to track unhandled errors</li>
</ol>



<!--
            <br/>
<hr/>
<h2>
    Prácticas Propuestas
</h2>
<ol reverse>

  
  <li> 
    <a href="/tema0-presentacion/practicas/pb-gh-campus-expert">GitHub Campus Expert</a> 
    <ul>
      <li>Repos en GH: <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/repositories?q=github-campus-expert&type=all&language=&sort=" target="_blank">github-campus-expert</a></li>
      <li><a href="/tema0-presentacion/practicas/pb-gh-campus-expert#rúbrica">Rúbrica</a> </li>
    </ul>
  </li>
  

  
  <li> 
    <a href="/tema1-introduccion/practicas/markdown">Learning Markdown</a> 
    <ul>
      <li>Repos en GH: <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/repositories?q=aprender-markdown&type=all&language=&sort=" target="_blank">aprender-markdown</a></li>
      <li><a href="/tema1-introduccion/practicas/markdown#rúbrica">Rúbrica</a> </li>
    </ul>
  </li>
  

  
  <li> 
    <a href="/tema1-introduccion/practicas/setup">Setting up Our Environment</a> 
    <ul>
      <li>Repos en GH: <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/repositories?q=setup&type=all&language=&sort=" target="_blank">setup</a></li>
      <li><a href="/tema1-introduccion/practicas/setup#rúbrica">Rúbrica</a> </li>
    </ul>
  </li>
  

  
  <li> 
    <a href="/tema1-introduccion/practicas/intro2sd">Introduction to Systems Development</a> 
    <ul>
      <li>Repos en GH: <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/repositories?q=intro2sd&type=all&language=&sort=" target="_blank">intro2sd</a></li>
      <li><a href="/tema1-introduccion/practicas/intro2sd#rúbrica">Rúbrica</a> </li>
    </ul>
  </li>
  

  
  <li> 
    <a href="/tema1-introduccion/practicas/jekyll-search">Search in Jekyll</a> 
    <ul>
      <li>Repos en GH: <a href="https://github.com/orgs/ULL-ESIT-DMSI-2425/repositories?q=jekyll-search&type=all&language=&sort=" target="_blank">jekyll-search</a></li>
      <li><a href="/tema1-introduccion/practicas/jekyll-search#rúbrica">Rúbrica</a> </li>
    </ul>
  </li>
  

</ol>



<br/>
<hr/>
<h2>
    Clases
</h2>

<ol reversed>
  
<li> <a href="/2024/10/07/leccion.html">Clase del Lunes 2024/10/07</a></li>
  
<li> <a href="/2024/10/02/leccion.html">Clase del Miércoles 2024/10/02</a></li>
  
<li> <a href="/2024/09/30/leccion.html">Clase del Lunes 2024/09/30</a></li>
  
<li> <a href="/2024/09/25/leccion.html">Clase del Miércoles 2024/09/25</a></li>
  
<li> <a href="/2024/09/23/leccion.html">Clase del Lunes 2024/09/23</a></li>
  
<li> <a href="/2024/09/18/leccion.html">Clase del Miércoles 2024/09/18</a></li>
  
<li> <a href="/2024/09/16/leccion.html">Clase del Lunes 2024/09/16</a></li>
  
</ol>


<br/>
<hr/>
-->

</section>
</div>

    
</body>

</html>
